### ISSUE TITLE
Search pagination issue

### ISSUE THREAD

**Issue by jelmersmid** [myspace-nu/jquery.fancyTable#6] opened 2019-10-03 08:46 UTC
Hi Thanks for your work.

Codepen example:
Copy a $name from page 1,
Browse to page 20 for example.
Search for $name and no result will show up except for when clicking the pagination page 1.

I tried to activate page one after search to no avail.

**Comment by myspace-nu** [comment] 2019-12-13 10:09
Thanks for the report! The issue is resolved in the latest version.

**Closed by myspace-nu** 2019-12-13 10:09 UTC
Labels: bug
